# Generated by Django 5.2.10 on 2026-02-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('total_emails', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sending', 'En cours'), ('completed', 'Terminé'), ('paused', 'En pause'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('send_speed', models.IntegerField(default=3600, help_text='Emails par heure')),
                ('use_time_window', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='email_generation.generatedemail')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='email_generation.emailsendingqueue')),
            ],
            options={
                'verbose_name': "Journal d'envoi",
                'verbose_name_plural': "Journaux d'envoi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sending', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sending_info', to='email_generation.generatedemail')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='email_sende_status_e598fd_idx'), models.Index(fields=['generated_email'], name='email_sende_generat_ee3b44_idx')],
            },
        ),
    ]
