"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#HOST_NAME_ID = '192.168.1.39'
HOST_NAME_ID = os.getenv("HOST_MACHINE", "host.docker.internal")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-development-key')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

#ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')
#ALLOWED_HOSTS =  ["*"] #os.environ.get("ALLOWED_HOSTS", "localhost").split(",")
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",


    "django_backend",
    "backend",
    "nginx",
    "nginx_server",
    
    "192.168.1.39",
    "192.168.1.62",
    
    "*",
    
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    
    'rest_framework',
    'corsheaders',
    'django_filters',
    
    'data_importer',
    'core',     
    'email_generation',
    'email_sender',
    'email_dispatcher',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# or 
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://192.168.1.39:8080",

    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.1.39:3000",

    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://192.168.1.39:5173",

]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASE_ROUTERS = ['data_importer.db_routers.SourceRouter']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'source_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('SOURCE_DB_NAME', 'odoo_test_full'),
        'USER': os.getenv('SOURCE_DB_USER', 'auto_mail_user'),
        'PASSWORD': os.getenv('SOURCE_DB_PASSWORD', 'odoo'),
        'HOST': os.getenv('SOURCE_DB_HOST', '192.168.1.39'),
        'PORT': os.getenv('SOURCE_DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# AWS SES Configuration
AWS_SES_CONFIG = {
    'ACCESS_KEY': os.getenv('AWS_ACCESS_KEY_ID'),
    'SECRET_KEY': os.getenv('AWS_SECRET_ACCESS_KEY'),
    'REGION': os.getenv('AWS_SES_REGION', 'us-east-1'),
    'SENDER_EMAIL': os.getenv('SENDER_EMAIL', 'no-reply@yourcompany.com'),
}

#############################
#############################
#############################

# LLM Configuration
OLLAMA_API_URL = os.getenv('OLLAMA_API_URL', f'http://{HOST_NAME_ID}:11434')
#OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'llama3.1:8b-instruct-q4_K_M')
OLLAMA_MODEL = "llama3.2"#"mistral:7b-instruct-q4_K_M"
OLLAMA_MODEL_NAME = os.getenv('OLLAMA_MODEL', OLLAMA_MODEL)
#OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'llama3.2:latest')

# OpenAI Configuration (optional)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Alternative LLM providers
# ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
# GOOGLE_AI_API_KEY = os.environ.get('GOOGLE_AI_API_KEY', '')

# Email generation settings
EMAIL_GENERATION_SETTINGS = {
    'default_model': 'simple',  # 'openai', 'anthropic', 'google', 'simple'
    'max_tokens': 1000,
    'temperature': 0.7,
    'timeout': 30,
}


#############################
#############################
#############################


#############################
#### CELERY
#############################
# Celery Configuration
# settings.py

# Celery Configuration for Remote Redis
#REDIS_HOST = REDIS_HOST = os.getenv("REDIS_HOST", "host.docker.internal")  # Replace with your Redis server IP
#REDIS_HOST='192.168.1.39'
#REDIS_PORT='6379'
REDIS_HOST = os.getenv("REDIS_HOST", "redis")  # default to redis container
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))

CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
REDIS_PASSWORD = None  # Add if you set a password
REDIS_DB = 0

# Construct Redis URL
if REDIS_PASSWORD:
    CELERY_BROKER_URL = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
    CELERY_RESULT_BACKEND = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
else:
    CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
    CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

# Optional: Add socket timeout
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'socket_timeout': 5,
    'socket_connect_timeout': 5,
}

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Task timeouts
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60


##############################################
##############################################
TURBOSMTP_CONSUMER_KEY = os.environ.get('TURBOSMTP_CONSUMER_KEY', '')
TURBOSMTP_CONSUMER_SECRET = os.environ.get('TURBOSMTP_CONSUMER_SECRET', '')
TURBOSMTP_WEBHOOK_SECRET = os.environ.get('TURBOSMTP_WEBHOOK_SECRET', '')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', '')
DEFAULT_REPLY_TO = os.environ.get('DEFAULT_REPLY_TO', '')
DEFAULT_FROM_NAME = os.environ.get('DEFAULT_FROM_NAME', 'BMM')


#TURBOSMTP_WEBHOOK_SECRET = "https://bmm.ma/webhook/turbosmtp/"

# Default sender
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'contact@bmm.ma')
DEFAULT_FROM_NAME = os.environ.get('DEFAULT_FROM_NAME', 'BMM')