# Generated by Django 5.2.10 on 2026-02-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='x_capital',
            field=models.CharField(blank=True, db_column='x_Capital', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='x_if',
            field=models.CharField(blank=True, db_column='x_IF', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='x_rc',
            field=models.CharField(blank=True, db_column='x_RC', max_length=255, null=True),
        ),
    ]
