# Generated by Django 5.2.10 on 2026-03-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='x_Capital',
            field=models.CharField(blank=True, max_length=255, null=True
                                  #, db_column='x_Capital'
                                   ),
        ),
    ]
