# Generated by Django 5.2.10 on 2026-02-24 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du lot')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('send_speed', models.IntegerField(default=3600, help_text='0 = pas de limite', verbose_name='Emails par heure')),
                ('use_time_window', models.BooleanField(default=False, verbose_name='Utiliser une fenêtre horaire')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('default_from_email', models.EmailField(max_length=254, verbose_name='Expéditeur par défaut')),
                ('default_from_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom expéditeur par défaut')),
                ('default_reply_to', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Répondre à par défaut')),
                ('total_emails', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('paused', 'En pause'), ('cancelled', 'Annulé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.TextField(blank=True, null=True, verbose_name='Métadonnées (JSON)')),
            ],
            options={
                'verbose_name': "Lot d'emails",
                'verbose_name_plural': "Lots d'emails",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('to_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du destinataire')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Expéditeur')),
                ('from_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'expéditeur")),
                ('reply_to', models.EmailField(blank=True, help_text="Si vide, utilise l'expéditeur", max_length=254, null=True, verbose_name='Répondre à')),
                ('subject', models.CharField(max_length=998, verbose_name='Sujet')),
                ('body_text', models.TextField(blank=True, verbose_name='Corps texte')),
                ('body_html', models.TextField(blank=True, verbose_name='Corps HTML')),
                ('message_id', models.CharField(blank=True, max_length=255, verbose_name='ID du message')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('processing', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Planifié pour')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='email_dispatcher.emailbatch')),
            ],
            options={
                'verbose_name': 'Message email',
                'verbose_name_plural': 'Messages email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=50)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='email_dispatcher.emailbatch')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='email_dispatcher.emailmessage')),
            ],
            options={
                'verbose_name': "Journal d'envoi",
                'verbose_name_plural': "Journaux d'envoi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status'], name='email_dispa_status_4185d1_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['to_email'], name='email_dispa_to_emai_6b4e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['batch'], name='email_dispa_batch_i_3f41ab_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['scheduled_at'], name='email_dispa_schedul_bbb6ad_idx'),
        ),
    ]
