# Generated by Django 5.2.10 on 2026-02-25 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('send_speed', models.IntegerField(default=3600, help_text='Emails per hour')),
                ('use_time_window', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('distribution_method', models.CharField(choices=[('spread', 'Spread across window'), ('fixed_delay', 'Fixed delay')], default='spread', max_length=20)),
                ('fixed_delay_seconds', models.IntegerField(default=1)),
                ('total_emails', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sending', 'En cours'), ('completed', 'Terminé'), ('completed_with_errors', 'Terminé avec erreurs'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=25)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_data', models.JSONField(default=dict)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.EmailField(max_length=254)),
                ('reply_to_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('queued', 'Dans la file'), ('sending', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('batch_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='email_dispatcher.dispatchbatch')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_emails', to='data_importer.recipient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('response', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_dispatcher.dispatchbatch')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='email_dispatcher.dispatchemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispatchemail',
            index=models.Index(fields=['status'], name='email_dispa_status_e89e77_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchemail',
            index=models.Index(fields=['batch'], name='email_dispa_batch_i_595c10_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchemail',
            index=models.Index(fields=['recipient_email'], name='email_dispa_recipie_c60d96_idx'),
        ),
    ]
