# Generated by Django 5.2.10 on 2026-02-24 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('send_speed', models.IntegerField(default=50, help_text='Emails per hour')),
                ('use_time_window', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_emails', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sending', 'En cours'), ('completed', 'Terminé'), ('paused', 'En pause'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='email',
        ),
        migrations.CreateModel(
            name='DispatchEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField()),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_data', models.JSONField(default=dict)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.EmailField(max_length=254)),
                ('reply_to_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('queued', 'Dans la file'), ('sending', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('batch_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='email_dispa_status_e89e77_idx'), models.Index(fields=['batch_id'], name='email_dispa_batch_i_595c10_idx'), models.Index(fields=['recipient_email'], name='email_dispa_recipie_c60d96_idx')],
            },
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('response', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='email_dispatcher.dispatchbatch')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='email_dispatcher.dispatchemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EmailBatch',
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
