# Generated by Django 5.2.10 on 2026-02-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('recipients_imported', models.IntegerField(default=0)),
                ('total_recipients', models.IntegerField(default=0)),
                ('emails_generated', models.IntegerField(default=0)),
                ('emails_failed_generation', models.IntegerField(default=0)),
                ('emails_in_queue', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_failed_sending', models.IntegerField(default=0)),
                ('emails_ready', models.IntegerField(default=0)),
                ('categories_used', models.JSONField(blank=True, default=dict)),
                ('avg_generation_time', models.FloatField(default=0)),
                ('avg_sending_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique quotidienne',
                'verbose_name_plural': 'Statistiques quotidiennes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_count', models.IntegerField(default=0, verbose_name="Nombre d'emails")),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='EmailGenerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la tâche')),
                ('total_emails', models.IntegerField(default=0)),
                ('processed_emails', models.IntegerField(default=0)),
                ('failed_emails', models.IntegerField(default=0)),
                ('total_categories', models.IntegerField(default=0)),
                ('current_category', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'File de génération',
                'verbose_name_plural': 'Files de génération',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSendingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la campagne')),
                ('total_emails', models.IntegerField(default=0)),
                ('sent_emails', models.IntegerField(default=0)),
                ('failed_emails', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'Envoi en cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('email_subject', models.CharField(blank=True, max_length=500)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "File d'envoi",
                'verbose_name_plural': "Files d'envoi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('subject_template', models.CharField(max_length=500)),
                ('body_template', models.TextField()),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('model_used', models.CharField(default='llama3.1', max_length=100)),
                ('prompt_used', models.TextField(blank=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Template d'email",
                'verbose_name_plural': "Templates d'email",
            },
        ),
        migrations.CreateModel(
            name='EmailGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('recipient_ids', models.TextField(default='[]')),
                ('selected_category', models.CharField(blank=True, max_length=255, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('total_categories', models.IntegerField(default=0)),
                ('current_category', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROGRESS', 'En cours'), ('SUCCESS', 'Terminé'), ('FAILURE', 'Échec'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('progress_info', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='email_generation.emailgenerationqueue')),
            ],
            options={
                'verbose_name': 'Tâche de génération',
                'verbose_name_plural': 'Tâches de génération',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_generation', 'En attente de génération'), ('generating', 'Génération en cours'), ('generated', 'Généré'), ('ready', 'Prêt à envoyer'), ('sending', 'Envoi en cours'), ('sent', 'Envoyé'), ('failed_generation', 'Échec génération'), ('failed_sending', 'Échec envoi'), ('cancelled', 'Annulé')], default='pending_generation', max_length=30)),
                ('queue_position', models.IntegerField(blank=True, null=True)),
                ('generation_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sending_task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_emails', to='data_importer.recipient')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_generation.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email généré',
                'verbose_name_plural': 'Emails générés',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['status', 'generated_at'], name='email_gener_status_604e30_idx'), models.Index(fields=['recipient', 'status'], name='email_gener_recipie_a3bee2_idx')],
                'unique_together': {('recipient', 'category_name')},
            },
        ),
    ]
