# Generated by Django 5.2.10 on 2026-01-30 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('prompt_template', models.TextField(help_text='LLM prompt template with {placeholders}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('body_html', models.TextField()),
                ('body_text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('sent', 'Sent'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.CharField(blank=True, max_length=100)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('ses_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generated', 'Generated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('sent', 'Sent'), ('failed', 'Failed'), ('regenerated', 'Regenerated')], max_length=20)),
                ('performed_by', models.CharField(max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.generatedemail')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('last_interaction', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'subcategory'], name='app_recipie_categor_dd2163_idx'), models.Index(fields=['last_interaction'], name='app_recipie_last_in_85c6c3_idx')],
            },
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='app.recipient'),
        ),
        migrations.AddIndex(
            model_name='generatedemail',
            index=models.Index(fields=['status', 'generated_at'], name='app_generat_status_3de9db_idx'),
        ),
    ]
