# Generated by Django 5.2.10 on 2026-01-30 09:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category_filter', models.JSONField(blank=True, default=dict)),
                ('recipient_count', models.IntegerField(default=0)),
                ('email_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('followup', 'Follow-up'), ('newsletter', 'Newsletter'), ('promotional', 'Promotional'), ('notification', 'Notification')], default='followup', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='priority',
            field=models.IntegerField(default=1, help_text='1=Lowest, 5=Highest', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Schedule for future sending', null=True),
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorization'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='action',
            field=models.CharField(choices=[('imported', 'Imported'), ('generated', 'Generated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('regenerated', 'Regenerated'), ('bulk_action', 'Bulk Action')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.generatedemail'),
        ),
        migrations.AlterField(
            model_name='generatedemail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='generatedemail',
            index=models.Index(fields=['scheduled_for', 'status'], name='app_generat_schedul_13fcd8_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedemail',
            index=models.Index(fields=['priority', 'status'], name='app_generat_priorit_5951e0_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['is_active'], name='app_recipie_is_acti_3567b8_idx'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='app.emailcampaign'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['action', 'performed_at'], name='app_emaillo_action_16bf03_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['performed_by', 'performed_at'], name='app_emaillo_perform_d2e0b0_idx'),
        ),
    ]
