# Generated by Django 5.2.10 on 2026-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emailqueue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailQueue',
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['-imported_at']},
        ),
        migrations.RemoveIndex(
            model_name='recipient',
            name='app_recipie_categor_dd2163_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipient',
            name='app_recipie_last_in_85c6c3_idx',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='recipient',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipient',
            name='source_id',
            field=models.IntegerField(blank=True, help_text='ID from source database', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='x_activitec',
            field=models.CharField(blank=True, help_text='Category from source database', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='company',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='last_interaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['x_activitec'], name='app_recipie_x_activ_6904db_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['email'], name='app_recipie_email_8b5d89_idx'),
        ),
    ]
